version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "melen-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-o69qk6inkzoj"
s3_prefix = "melen-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
