import {
    attribute,
    autoGeneratedHashKey,
    rangeKey,
    table
} from "@aws/dynamodb-data-mapper-annotations";

@table("posts")
export class Post {
    @autoGeneratedHashKey()
    id: string

    @rangeKey()
    timestamp: number;

    @attribute()
    date: Date;

    @attribute()
    author: string;

    @attribute()
    title: string;

    @attribute()
    body: string

    // @attribute()
    // metadata: PostMetadata
}

export class PostMetadata {
    @attribute({memberType: 'String'})
    tags: Set<string>
}